### ISSUE TITLE
Esc in terminal window does not shift focus back to the document well.

### ISSUE THREAD

**Issue by dgriffen** [Microsoft/WhackWhackTerminal#15]
_From @clboles on July 28, 2017 14:22_

In VS tool windows, the Esc key generally returns focus back to the previously active document.  It would be nice if terminal window supported this as well since it's such a common muscle memory.

I wouldn't want to lose the behavior where Esc clears the input line in the terminal window, though.  Perhaps Esc should be special cased to support both.  If the user has typed input, then Esc should clear the line and keep focus in the terminal.  If there is no input, then Esc could release focus from the tool window.

_Copied from original issue: dgriffen/WhackWhackTerminal#13_

**Comment by dgriffen** [comment]
I'm not sure if this is a feature I can support. For simple terminal applications it would be trivial to contextualize it. But consider the case where a user has an application such as vim open. The esc key has an important function in vim and since vim uses ncurses to write text at various locations in the terminal window there is no reliable way to contextualize it. Users can always use Ctrl+Tab to navigate away from the terminal without a mouse.

**Comment by dgriffen** [comment]
_From @clboles on July 29, 2017 0:59_

Are you able to tell when an executable is running vs when just idling in the shell waiting for input?  I think it would be an acceptable tradeoff for Esc to only release focus when sitting idle and not in another console app.

The challenge you're going to continually encounter is terminal behavior conflicting with standard VS windowing/keyboard behavior.  Finding the right balance is going to be key to this feeling right in the IDE.  It's looking promising so far!

**Comment by dgriffen** [comment]
Unfortunately I don't think there is a way for me to determine if there is a currently running process from the interface I have available to me. I use node-pty as a backend and it doesn't appear to offer me any hooks to determine if there is a running process.

**Comment by dgriffen** [comment]
_From @Tyriar on August 3, 2017 5:59_

This should be closed as designed imo.

> If the user has typed input, then Esc should clear the line and keep focus in the terminal. If there is no input, then Esc could release focus from the tool window.

node-pty just provides an input and an output stream, to us/xterm.js there is no differentiating input, prompt and output. This is something I've been thinking of for quite a while though so it may eventually be solved. I recommend not bothering looking into this but instead tracking https://github.com/Microsoft/vscode/issues/20676 for updates, it is not anywhere near as trivial as it seems 😃 

> Unfortunately I don't think there is a way for me to determine if there is a currently running process from the interface I have available to me. 

This is true, even if there was I'd recommend against it as esc can be eaten by processes that are not the outer shell too. (eg. vim).

> The challenge you're going to continually encounter is terminal behavior conflicting with standard VS windowing/keyboard behavior. Finding the right balance is going to be key to this feeling right in the IDE. It's looking promising so far!

VS Code gets around this by having a concept of "commands to skip the shell"; a list of commands that will not be sent to be handled by xterm.js. I'm not sure if this would translate well to VS.

**Comment by armaandh** [comment]
> Users can always use Ctrl+Tab to navigate away from the terminal without a mouse.
Just a quick note...when i'm in the terminal, i'm unable to use Ctrl-Tab to navigate away. Only through the mouse clicking into the code window can I go back to work. From the code window, pressing Ctrl-Tab however brings up the switcher and lets me go back to terminal window without problems.

**Comment by dgriffen** [comment]
Closing as designed at the suggestion of @Tyriar.

@armaandh I just landed a fix that passes Ctrl+Tab through to VS
