### ISSUE TITLE
CTRL-C on a line when something isn't selected should send a break

### ISSUE THREAD

**Issue by dgriffen** [microsoft/WhackWhackTerminal#16]
_From @shanselman on August 2, 2017 18:46_

CTRL-C on a line when something isn't selected should send a break (that is, cancel the command and go to a clear line) instead of outputting ^c.

_Copied from original issue: dgriffen/WhackWhackTerminal#15_

**Comment by dgriffen** [comment]
It should currently be doing that. Can you give some more context into what you mean?

**Comment by dgriffen** [comment]
_From @shanselman on August 2, 2017 20:39_

Go into cmd.exe, type test, then ctrl-c. The command is cancelled and you get a new prompt. In WhackWhack you either get a "^C" output OR nothing happens.

**Comment by dgriffen** [comment]
test isn't recognized as a command for me. Is it a program you installed?

**Comment by dgriffen** [comment]
_From @Tyriar on August 3, 2017 6:7_

Here's the upstream issue https://github.com/Tyriar/node-pty/issues/7 for this. This is one of the problems that is very difficult because of the nature of the backing library [winpty](https://github.com/rprichard/winpty).

You can however press esc to reliably clear the line in cmd and powershell.

**Comment by dgriffen** [comment]
_From @shanselman on August 3, 2017 8:42_

Thanks @Tyriar.

@dgriffen It's not a exe, it's just text...try it in cmd.exe. Type some stuff and hit ctrl+C. It's different behavior from ESC as @Tyriar suggests.

**Comment by ghost** [comment]
Fixed as of #79
