### ISSUE TITLE
Add support for ANSI escape codes for colors

### ISSUE THREAD

**Issue by thomaslevesque** [Microsoft/WhackWhackTerminal#25]
ANSI escape codes are used by many console applications to specify the color of the output. Currently, WhackWhackTerminal doesn't support those codes, and outputs the escape sequences instead.

Expected result in the standard Powershell console (conhost):
![conhostoutput](https://user-images.githubusercontent.com/1864281/29945665-5fa24ee0-8ea2-11e7-93e7-562ddb34a319.png)

Actual result in WhackWhackTerminal:
![whackwhackoutput](https://user-images.githubusercontent.com/1864281/29945678-72e451a6-8ea2-11e7-88e6-e8f524ea2ce2.png)

(this is the output produced by [simple-targets-csx](https://github.com/adamralph/simple-targets-csx))

**Comment by dgriffen** [comment]
I have never seen this before in my testing. I should be handling escape code sequences properly. That was part of the entire purpose of this terminal. Can you create a minimal sample that reproduce this?

**Comment by dgriffen** [comment]
As an example, if i type `echo -e "\e[36msimple\e[39;49m"` into my bash prompt i get a properly colored output.

**Comment by dgriffen** [comment]
So I was able to reproduce this by running `build.cmd` in WhackWhackTerminal, but the strange thing is I got the same behavior when running in powershell and cmd. They didn't seem to be respecting the escape sequences. The output was similar to `[36msimple-targets[0m[37m: [0m[37mRunning "default"...[0m[95m (dry run)[0m`

**Comment by thomaslevesque** [comment]
I'm not sure... build.cmd uses csi.exe to execute a .csx script. I don't think it does any explicit escaping.

The code for producing the escape code is [here](https://github.com/adamralph/simple-targets-csx/blob/master/src/internal/util.csx)

**Comment by dgriffen** [comment]
So I tested the scenario with the following code:
```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program
    {
        private static string Default(bool color) => color ? "\x1b[0m" : "";
        private static string Green(bool color) => color ? "\x1b[32m" : "";

        static void Main(string[] args)
        {
            Console.WriteLine(GetColor());
        }

        private static string GetColor()
        {
            return $"{Green(true)}simple{Default(true)}";
        }
    }
}
```

The text prints fine in powershell, but not in cmd. Looking into the issue further is appears the problem is actually a C# limitation in how you are supposed to print to the console. I searched and found [this](https://social.msdn.microsoft.com/Forums/vstudio/en-US/e98c71d1-0b97-47a8-96de-645d58e2164d/console-escape-codes-especially-colors?forum=csharpgeneral) link. Which led me to [this](https://docs.microsoft.com/en-us/windows/console/writeconsole) page on the microsoft docs. It would seem that you are not supposed to print the ansi sequences directly, and while it may work its not guaranteed to.

**Comment by thomaslevesque** [comment]
> For example, i tested your build.cmd script on another windows 10 machine I had and colored output worked in WhackWhackTerminal and Powershell, but not CMD.

Weird... I just tried again in WWT, and now it works. I have no idea what could be causing this.

**Comment by dgriffen** [comment]
I think its some weird way that the underlying win32 APIs are detecting ANSI support and turning it on. For now I think your best course of action if you want this 100% consistent is to use the `Console.ForegroundColor` properties.

**Comment by thomaslevesque** [comment]
OK, thanks for investigating. Hopefully it won't happen too often...
