### ISSUE TITLE
Ctrl+O brings file open dialog, but after opening a file the window is no longer a terminal

### ISSUE THREAD

**Issue by dannyvv** [Microsoft/WhackWhackTerminal#26]
Repro:
1. Open the terminal
1. Hit Ctrl+O
1. Browse to any text file
1. Hit <enter> or <Ok> to open

Result:
* Text file is rendered in the console
  * There seems no way to go back to the interactive console
  * The only way to recover seems to be to restart Visual Studio

Expected:
* For my scenario it would be nice if Ctrl+O was not handled at all and the main VS shell would handle the open the file command.

**Comment by dgriffen** [comment]
This was a small issue that I knew about but I was waiting until there were reports to gauge the severity. Since I've got a report I'll start working on a fix.

**Comment by dannyvv** [comment]
Thanks! It's not a big deal, I know now to look for the difference in open dialog :) 
From my perspective feel free to prioritize below any other work, this project is saving me so much time! If it really bothered me I would have created a pull request :)

**Comment by dgriffen** [comment]
fixed in master
