### ISSUE TITLE
Who to change the font size?

### ISSUE THREAD

**Issue by iwhp** [Microsoft/WhackWhackTerminal#27]
Is there a way to change the font size?
Thankx, Harry

**Comment by dgriffen** [comment]
There is an option to use a custom css file to style the terminal. You can find an example file [here](https://github.com/Microsoft/WhackWhackTerminal/blob/master/EmbeddedTerminal/view/custom.css).

**Comment by dgriffen** [comment]
Is this an acceptable solution for you? Or would you like a setting specifically for font size. If the proposed solution works I'll close this issue.

**Comment by iwhp** [comment]
Thankx dgriffen! I did not realize that I can choose whatever css settings I like. So YES, the solution works for me. I am having this for the moment:

```
.terminal {
    color: default;
    font-familiy: Consolas;
    font-size: 12px;
    margin: 10px;
}
```
Maybe you should consider putting something into the default template, so one can see how it works.
