### ISSUE TITLE
Activating Alt key shortcuts prints the character in the terminal

### ISSUE THREAD

**Issue by justcla** [Microsoft/WhackWhackTerminal#33]
When I press Alt+W (to access the Window menu - to Dock/Float/etc), it prints a 'w' character in the terminal. When I press Alt+F, it prints an 'f'.
Can we have VS handle all Alt key shortcuts and not pass any to the terminal?

(Not sure if that's a good idea. I couldn't think of any reason to use an Alt shortcut in the terminal.)

**Comment by dgriffen** [comment]
I'll look into adding it as a preference that you can change but the current behavior will probably remain the default. I can't think of a reason that you might want Alt shortcuts in the terminal but there may be a reason that I am unaware of.

**Comment by justcla** [comment]
Given we can't find a good reason to use Alt keys in the terminal, and given that Alt keys are really useful for everything else - particularly accessing the Menu with accelerator keys, can we say this IS a desired feature that should be implemented (if time and energy permit)?

**Comment by dgriffen** [comment]
I do agree that this feature should be implemented. I just think that it shouldn't be the default (especially since VSCode behaves that way).

**Comment by justcla** [comment]
Well then, VS Code should change their behavior. At least for VS users, the default should be to let VS handle the Alt keys, otherwise a user's ability to use VS is hampered.
If there are users who want the Alt key handled by the terminal, they should opt-in to that behavior. (IMO)

**Comment by dgriffen** [comment]
Fixed, alt key combos no longer print in the terminal in 1.0

**Comment by justcla** [comment]
Thanks Daniel! :-D
