### ISSUE TITLE
Support for other consoles? 

### ISSUE THREAD

**Issue by drashna** [Microsoft/WhackWhackTerminal#36]
Namely MSYS/mingw.

**Comment by drashna** [comment]
Adding `/k C:\msys64\usr\bin\bash.exe --login -i` to the arguments work, mostly.  But it's detected as MSYS, not mingw64, which is a problem for me.

**Comment by dgriffen** [comment]
This is now supported via the `Tools>Options>WhackWhackTerminal` dialog in version 1.0
