### ISSUE TITLE
WhackWhackTerminal.Embeddable NuGet doesn't properly supply .targets file

### ISSUE THREAD

**Issue by IlyaBiryukov** [Microsoft/WhackWhackTerminal#48]
WhackWhackTerminal.Embeddable NuGet package v 1.0.11 has `build\Microsoft.VisualStudio.Terminal.Embeddable.targets` file, but it is not being imported. NuGet is looking for `build\WhackWhackTerminal.Embeddable.targets` instead. We need to rename the file.

**Comment by dgriffen** [comment]
I'm not able to replicate the behavior you're seeing. Both VSIX and .NET Framework Class Libraries properly add the <EmbedInteropAssemblies> tag. The only project type I can find that uses <PackageReference> is a .NET standard project which doesn't add the tag properly even after renaming the .targets file.

**Comment by IlyaBiryukov** [comment]
The support for build targets was added in Nuget 2.5. The file name must match the package id.
See [here](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-2.5#automatic-import-of-msbuild-targets-and-props-files)

**Comment by dgriffen** [comment]
I think I fixed this in #50
