### ISSUE TITLE
German keyboard binding for starting the terminal

### ISSUE THREAD

**Issue by MSeifert04** [Microsoft/WhackWhackTerminal#59]
It took me a while to figure out that on a german keyboard the command to start the terminal is Ctrl + ^ (twice). That's because the "keyboard-aware" key [`VK_OEM_5`](https://github.com/Microsoft/WhackWhackTerminal/blob/v1.0.14/Microsoft.VisualStudio.Terminal/TermWindowPackage.vsct#L61) is used.

It would have made starting to use this extension a lot easier/faster if it were documented on the [marketplace page](https://marketplace.visualstudio.com/items?itemName=DanielGriffen.WhackWhackTerminal) or in the ReadMe of this repo. I know that one can always inspect the keyboard-bindings in visual studio or browse the source but it feels a bit complicated.

**Comment by dgriffen** [comment]
I wasn't aware the binding I was using was "keyboard aware". In your opinion would it be better to switch to a non-keyboard aware binding or just document the current behavior?

**Comment by MSeifert04** [comment]
> In your opinion would it be better to switch to a non-keyboard aware binding or just document the current behavior?

Personally, I would prefer the documentation.

**Comment by dgriffen** [comment]
I documented it on the marketplace page. As far as I'm aware the best way to determine the active shortcut is to look at the menu entry for the window.
