### ISSUE TITLE
Set path to current solution when open terminal

### ISSUE THREAD

**Issue by mwinkler** [Microsoft/WhackWhackTerminal#6]
If i open the terminal (PowerShell), the current path is set to my users folder instead of the current solution folder.
How can i change this behavior?

**Comment by dgriffen** [comment]
If you have a solution currently open it should open to that automatically. If you open the solution after opening the terminal then it won't. Until I get a toolbar implemented you can always type `exit` in the terminal to restart it and it should open to your current solution.

**Comment by mwinkler** [comment]
Thanks, switch to current solutions folder with `exit` works fine. 
But per default, i'm always in my users folder (even if i open the terminal after the solution is loaded).

**Comment by dgriffen** [comment]
Odd, that's not how it should behave, I'll try and repro it on my end. I'm also going to try and come up with a better solution than typing `exit` to get to the solution directory.
