### ISSUE TITLE
Doesn't seem to work with Git Bash

### ISSUE THREAD

**Issue by asherber** [Microsoft/WhackWhackTerminal#80]
VS2019 16.1.1
WhackWhack 1.2.7.30024
Git for Windows 2.21.0.windows.1

I have Default Shell set to Other, and Shell Path set to "C:\Program Files\Git\git-bash.exe"

When I open the terminal window, I get a blinking block cursor in the upper left, and nothing else -- I'm not able to type in the terminal.

**Comment by ghost** [comment]
The `git-bash` executable is actually a GUI program that launches its own console window, which is why it doesn't seem to work. As per https://github.com/microsoft/vscode/issues/7286 you should set the path to `C:\Program Files\Git\bin\bash.exe`
