### ISSUE TITLE
Command Terminal Window is unavailable

### ISSUE THREAD

**Issue by TheJayMann** [Microsoft/WhackWhackTerminal#82]
I am currently unable to bring up the terminal window via keyboard shortcut and have been unable to do so for some time.  I don't remember when it stopped working (it was possibly around the 16.3 update), but it still does not work as of 16.3.5.  The message on the bottom of the Visual Studio window states "The key combination (Ctrl+\, Ctrl+\) is bound to the command (Terminal Window) which is not currently available."  When I add the View.TerminalWindow command to a menu item under View -> Other Windows, the Terminal Window option appears disabled.  I am able to access it by using Visual Studio search, or by clicking on the tab if it is currently open.

**Comment by alandraper** [comment]
Same problem here. Terminal window appears gray and with a solid cursor, but typing does nothing. Also Ctrl+\\, Ctrl+\\ does not work.

**Comment by asherber** [comment]
When I went to Options | Keyboard and searched for "terminal", I could see that there were two commands called `View.TerminalWindow`. One of them had the `Ctrl+\, Ctrl+\` shortcut assigned, and the other did not.

I removed the shortcut from the one that had it and added it to the other one, and now everything works for me as expected.

**Comment by ghost** [comment]
This was due to the 16.3 version using `Ctrl+\, Ctrl+\` as a placeholder shortcut for the built-in terminal. This has been rectified in 16.4 since the built-in terminal now uses Ctrl+`

**Comment by alandraper** [comment]
I tried uninstalling & reinstalling, but still get the gray disabled Terminal window that can't be typed in. 

![image](https://user-images.githubusercontent.com/13674761/68907251-fed2b080-06fb-11ea-88c8-be1962e38337.png)

**Comment by ghost** [comment]
@alandraper your issue is separate since the command is available and I believe is tracked by #81
