### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by vivekvardhanadepu** [Microsoft/WhackWhackTerminal#84]
How to change font?

**Comment by ghost** [comment]
Its in the Tools>Options settings for the extension

**Comment by vivekvardhanadepu** [comment]
![Screenshot (152)](https://user-images.githubusercontent.com/32814044/71600364-9d17ba00-2b74-11ea-833a-536fe85b761a.png)
There is this font family. But, only one font is present

**Comment by ghost** [comment]
You can enter any text you want in that area. It follows the CSS rules for font family

**Comment by vivekvardhanadepu** [comment]
Thanks a lot
