### ISSUE TITLE
Just get a blinking cursor in the terminal window

### ISSUE THREAD

**Issue by dr3x** [Microsoft/WhackWhackTerminal#88]
Visual Studio Community 2019
Version 16.6.2

When I invoke terminal, I get a new tab with a blinking cursor but no terminal.
This happens whether it is invoked as a regular terminal or when I'm trying to shell into a Docker container
Nothing I do in the tab window gets me a proper prompt

**Comment by ghost** [comment]
As of 16.6 you should be using the built in terminal instead of this extension.

**Comment by dr3x** [comment]
@ZoeyR ok does it not work?  Using the built in terminal I get the message that "Integrated terminal is not installed.  External terminal has started instead." And then a link to install this...

**Comment by ghost** [comment]
That isn't a message built into the integrated terminal. How are you launching the built in terminal?

**Comment by dr3x** [comment]
By clicking on the terminal icon on the containers window:
![image](https://user-images.githubusercontent.com/829901/86962855-666cbe80-c118-11ea-8a0b-b81c728bf038.png)

**Comment by ghost** [comment]
Oh, that would be a bug in the containers window. I recommend sending feedback via VS directly.
